#ifndef KEYSTONE_EXAMPLES_EXPORT_H
#define KEYSTONE_EXAMPLES_EXPORT_H

#define PARAMS_BIN_LEN 50947938
#define PARAMS_BIN_PAD_LEN 50950144
#define GRAPH_JSON_LEN 162272
#define GRAPH_JSON_PAD_LEN 163840

// Just some command definitions
enum {
    EXPORT_SETUP,
    EXPORT_INFER,
    EXPORT_DIE
};

#endif //KEYSTONE_EXAMPLES_EXPORT_H
